version: '3.8'

volumes:
  postgres-data:
  postgres-data-backups:

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: messaging-api-postgres-data
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-data-backups:/backups
    env_file:
      - ./.env
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile.prod
    image: messaging-api-backend
    volumes:
      - .:/usr/src/app
    command: /usr/src/app/docker/django/start_production
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: unless-stopped
